// Generated by CoffeeScript 1.6.3
var MovementSystem;

MovementSystem = (function() {
  function MovementSystem() {}

  MovementSystem.prototype.update = function(delta, entityManager) {
    var arrows, entities, entity, position, velocity, _i, _len, _results;
    entities = entityManager.getEntitiesWithComponents(['PositionComponent', 'VelocityComponent', 'ArrowKeyInputComponent']);
    _results = [];
    for (_i = 0, _len = entities.length; _i < _len; _i++) {
      entity = entities[_i];
      position = entityManager.getComponent(entity, 'PositionComponent');
      velocity = entityManager.getComponent(entity, 'VelocityComponent');
      arrows = entityManager.getComponent(entity, 'ArrowKeyInputComponent');
      console.log(arrows.up);
      velocity.dx = velocity.dy = 0;
      if (arrows.left) {
        velocity.dx -= velocity.maxSpeed * delta;
      }
      if (arrows.right) {
        velocity.dx += velocity.maxSpeed * delta;
      }
      if (arrows.up) {
        velocity.dy -= velocity.maxSpeed * delta;
      }
      if (arrows.down) {
        velocity.dy += velocity.maxSpeed * delta;
      }
      position.x += velocity.dx;
      _results.push(position.y += velocity.dy);
    }
    return _results;
  };

  return MovementSystem;

})();
